# Configuration file for the pre-commit tool
# It is used to run tests on CI and on your machine
#
# installation: pip install pre-commit
#
# setup: pre-commit install
#
# Now tests will be run automatically at each commit
# Or you can run the tests with: pre-commit run -a
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-xml
    - repo: local
      hooks:
          - id: autopep8
            name: autopep8
            entry: autopep8
            language: system
            types_or: [python]
            require_serial: true
            args: ["-i"]
          - id: isort
            name: isort
            entry: isort
            language: system
            types_or: [python, pyi]
            require_serial: true
            args: ['--filter-files']
          - id: mypy
            name: mypy
            entry: mypy
            language: system
            types_or: [python, pyi]
            require_serial: true
            args: ["--scripts-are-modules"]
          - id: unittest
            name: unit tests
            entry: python -m unittest
            language: system
            pass_filenames: false
            verbose: true
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types_or: [python]
            require_serial: true
            args: [
              "-rn", # Only display the messages
              "-sn", # Don't display the score
            ]
